[package]
name = "gfa-games"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["tictactoe", "connect4", "sudoku", "chess"]
tictactoe = ["dep:gfa-game-tictactoe"]
connect4 = ["dep:gfa-game-connect4"]
sudoku = ["dep:gfa-game-sudoku"]
chess = ["dep:gfa-game-chess"]

[dependencies]
gfa-core.workspace = true
gfa-game-tictactoe = { workspace = true, optional = true }

gfa-game-connect4 = { workspace = true, optional = true }

gfa-game-sudoku = { workspace = true, optional = true }
gfa-game-chess = { workspace = true, optional = true }

[lints]
workspace = true
