from typing import Any

def games() -> list[str]: ...

class NativeEnv:
    game_id: str
    action_space_size: int
    num_players: int
    def __init__(self, game_id: str, config_json: str = "{}", seed: int = 0) -> None: ...
    def reset(self, seed: int = 0, position: str | None = None) -> None: ...
    def step(self, seat: int, action: int) -> tuple[list[float], bool, bool]: ...
    def step_string(self, seat: int, action: str) -> tuple[list[float], bool, bool]: ...
    def current_players(self) -> list[int]: ...
    def flags(self) -> tuple[bool, bool]: ...
    def returns(self) -> list[float]: ...
    def frame(self, seat: int) -> dict[str, Any]: ...
    def public_text(self) -> str: ...
    def clone(self) -> NativeEnv: ...
    def get_state(self) -> str: ...
    def set_state(self, snapshot: str) -> None: ...

def position_set_data(name: str) -> tuple[str, str]: ...
