from typing import Any

def games() -> list[str]: ...

class NativeEnv:
    game_id: str
    action_space_size: int
    num_players: int
    def __init__(self, game_id: str, config_json: str = "{}", seed: int = 0) -> None: ...
    def reset(self, seed: int = 0, position: str | None = None) -> None: ...
    def step(self, seat: int, action: int) -> tuple[list[float], bool, bool]: ...
    def step_string(self, seat: int, action: str) -> tuple[list[float], bool, bool]: ...
    def spec_json(self) -> str: ...
    def current_players(self) -> list[int]: ...
    def flags(self) -> tuple[bool, bool]: ...
    def returns(self) -> list[float]: ...
    def frame(self, seat: int) -> dict[str, Any]: ...
    def public_text(self) -> str: ...
    def clone(self) -> NativeEnv: ...
    def get_state(self) -> str: ...
    def set_state(self, snapshot: str) -> None: ...

class NativeVectorEnv:
    n: int
    num_players: int
    action_space_size: int
    def __init__(self, game_id: str, n: int, config_json: str = "{}", seed: int = 0, threads: int = 0) -> None: ...
    def frame(self, seats: list[int] | None = None) -> dict[str, Any]: ...
    def step(self, actions: list[int | None]) -> dict[str, Any]: ...
    def reset_at(self, indices: list[int], seeds: list[int], positions: list[str | None]) -> dict[str, Any]: ...
    def clone(self) -> NativeVectorEnv: ...
    def get_state(self) -> list[str]: ...
    def set_state(self, snapshots: list[str]) -> None: ...

def position_set_data(name: str) -> tuple[str, str]: ...
