//! Available players and bounded, observation-scoped engine analysis.
use crate::{empty_config, SimulationFrom};
use gfa_core::LegalAction;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Measured strength at one resource level, absent until a calibration exists.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct OpponentLevel {
    /// Resource level from 1 through 10.
    pub level: u8,
    /// Published rating, never an estimate invented from search depth.
    pub rating: Option<f64>,
}

/// Opponent available for this installed game and host.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
pub struct OpponentSpec {
    /// Stable player identifier.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Supported resource levels; empty for a player without a difficulty ladder.
    pub levels: Vec<OpponentLevel>,
    /// Whether the ladder has been measured in a published calibration run.
    pub calibrated: bool,
}

/// Optional overrides of a level's hard search budget.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SearchBudget {
    /// Maximum nodes, 1..1000000.
    #[cfg_attr(feature = "openapi", schema(minimum = 1, maximum = 1000000))]
    pub nodes: Option<u64>,
    /// Maximum search depth, 1..64.
    #[cfg_attr(feature = "openapi", schema(minimum = 1, maximum = 64))]
    pub depth: Option<u8>,
    /// Maximum elapsed search time, 1..60000 milliseconds.
    #[cfg_attr(feature = "openapi", schema(minimum = 1, maximum = 60000))]
    pub time_ms: Option<u64>,
}

/// Reproducible player selection, also used when assigning opponent seats.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct OpponentConfig {
    /// Identifier from the game-specific opponent catalog.
    pub id: String,
    /// Search level, defaulting to 3. Random has no levels.
    #[serde(default)]
    #[cfg_attr(feature = "openapi", schema(minimum = 1, maximum = 10))]
    pub level: Option<u8>,
    /// Optional hard limits; seed is supplied independently from live match RNG.
    #[serde(default)]
    pub limits: SearchBudget,
}

/// Analyze one authorized position without applying moves to its match.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct AnalysisRequest {
    /// Registered game.
    pub game_id: String,
    /// Match observation or caller-supplied position/state.
    pub from: SimulationFrom,
    /// Standalone options; omitted for a match source.
    #[serde(default = "empty_config")]
    pub config: Value,
    /// Requested player and hard search limits.
    pub opponent: OpponentConfig,
    /// Independent planning seed, generated by the host when omitted.
    #[serde(default)]
    pub seed: Option<u64>,
}

/// A legal recommendation with measured search diagnostics.
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct AnalysisResult {
    /// Registered game.
    pub game_id: String,
    /// Opponent identifier.
    pub opponent: String,
    /// Independent planning seed.
    pub seed: u64,
    /// Recommended legal actions in order of preference.
    pub best_moves: Vec<LegalAction>,
    /// Expected return for the requesting seat, absent without completed search.
    pub evaluation: Option<f64>,
    /// Canonical continuation, beginning with the recommended action.
    pub principal_variation: Vec<String>,
    /// Visited nodes.
    pub nodes: u64,
    /// Completed search depth.
    pub depth: u8,
    /// Whether a hard resource bound interrupted search.
    pub budget_exhausted: bool,
}
