[package]
name = "gfa-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gfa-api-types.workspace = true
gfa-service.workspace = true
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
gfa-core.workspace = true
tokio.workspace = true
tempfile.workspace = true

[lints]
workspace = true
